# SPDX-License-Identifier: GPL-2.0

dts-dirs += palette/o1q
dts-dirs += palette/t2q
dts-dirs += palette/p3q

always          := $(dtb-y)
subdir-y        := $(dts-dirs)

clean-files := *.dtb *.reverse.dts *.dtbo

